name: ivar

channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - snakemake-minimal >=5.24.1
  - bcftools =1.9
  - graphviz
  - samtools =1.9
  - bwa =0.7
  - ivar
  - fastqc
  - bbmap
  - spades
  - pandas
  - python=3.7.8
